<a href="https://colab.research.google.com/github/alphoenixbiz/Machine-Learning-Using-Python/blob/master/Linear%20Regression/Example%203/Linear_Regression_example3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
%matplotlib inline

In [42]:
df = pd.read_csv("gdrive/My Drive/Colab Notebooks/hiring.csv")
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [43]:
import math
median_ts= math.floor(df['test_score(out of 10)'].median())
median_ts

8

In [44]:

df['test_score(out of 10)'] = df['test_score(out of 10)'].fillna(median_ts)
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    8.0                           7      72000
7     eleven                    7.0                           8      80000

In [45]:
df['experience'] = df['experience'].fillna('zero')
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0       zero                    8.0                           9      50000
1       zero                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    8.0                           7      72000
7     eleven                    7.0                           8      80000

In [46]:
pip install word2number

In [0]:
from word2number import w2n

In [0]:
def covertTonumber(x):
    return w2n.word_to_num(x)

In [0]:
df['experience'] = df['experience'].apply(covertTonumber)


In [50]:
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    8.0                           7      72000
7          11                    7.0                           8      80000

In [0]:
from sklearn import linear_model
reg = linear_model.LinearRegression()

In [64]:
X = df.drop('salary($)', axis=1).values
y = df['salary($)'].values.reshape(-1,1)
y

array([[50000],
       [45000],
       [60000],
       [65000],
       [70000],
       [62000],
       [72000],
       [80000]])

In [70]:
reg.fit(X,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [66]:
reg.coef_

array([[2812.95487627, 1845.70596798, 2205.24017467]])

In [67]:
reg.intercept_

array([17737.26346434])

In [68]:
reg.predict([[12,8,5]])

array([[77284.5705968]])